## ref: https://backstage.io/docs/features/techdocs/creating-and-publishing#manually-add-documentation-setup-to-already-existing-repository
site_name: 'micronaut-greeter'

nav:
  - index.md
  - details.md

plugins:
  - techdocs-core
